[package]
name = "sjdinsd/temp"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@3.1.1"
sift = "csqrl/sift@0.0.11"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
# networker = "leifstout/networker@0.3.0"
react-ripple = "littensy/react-ripple@3.0.1"
react-charm = "littensy/react-charm@0.3.0"
charm = "littensy/charm@^0.10"
dataservice = "leifstout/dataservice@0.4.0"
# charm-sync = "littensy/charm-sync@0.3.0"
janitor = "howmanysmall/janitor@1.18.3"
ui-labs = "pepeeltoro41/ui-labs@2.4.2"
ripple = "littensy/ripple@0.10.1"